version: '2'

services:
  civicrm:
    restart: always
    build:
      context: ./civicrm
      args:                                                       
        STYLING: ${STYLING}
    ports:
      - "80:80"
    volumes:
      - ./lcbru_civicrm:/lcbru_civicrm
    env_file: .env
