version: '2'

services:
  civicrm:
    restart: always
    build: ./civicrm
    ports:
      - "80:80"
    volumes:
      - ./lcbru_civicrm:/lcbru_civicrm
    environment:
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DRUPAL_DATABASE
      - MYSQL_CIVICRM_DATABASE
      - DRUPAL_ACCOUNT_MAIL
      - DRUPAL_ACCOUNT_NAME
      - DRUPAL_ACCOUNT_PASS
      - DRUPAL_SITE_MAIL
      - DRUPAL_SITE_NAME
      - ENABLED_PACKAGES
      - BASE_URL
      - INSTALL_DATABASE
      - INSTALL_TEST_DATA